### ISSUE TITLE
idea  to lower docker image size

### ISSUE THREAD

**Issue by malocharo** [TuxML/ProjetIrma#108]
We could test those idea to lower the docker image size and reduce the download's time.

compress the kernel inside the docker image and decompress it on the user's computer. 

compress all the dependencies and decompress and build the docker image on the user's computer.

The idea behind it, is that it's faster to decompress and build a docker image on the computer than download a full build version and the kernel.

**Comment by alemasle** [comment]
When you update the docker image, it is pushed to the docker hub and everybody will automatically download the last version when MLfood.py runs. If you compress the kernel, each compilation run on a new container will have to decompress.

Sending one full working image will be more efficient than compress to send faster but decompress in each compilation will slow down a lot.

**Comment by mipicard** [comment]
But what if we can test if we have an update, and rebuild the image in that case?

We won't lose so much time, because the image will be rebuilt once, and not for every compilation.
Yes, it can be bothersome when using dev image, but for global user, you will use prod image, ie an image who will not be change a lot of time.
Also, I think that it's faster to rebuild the image if needed : for low quality internet, it's usefull, because downloading at 50ko/s take more than 30min to do so, when you will probably spend less if you build it internally.

So I personnaly think that this idea could be tested.
For backward compatibility (and if it's successful), it can be offer as an option in the command line.

But netherless, we need to know if we can check if yes or no we really update the underlying image.
If yes, it can be an option. If not, we possibly can forgot that idea.

**Comment by alemasle** [comment]
We talked about that, we tried to force a `git pull` at each compilation in the "dev" image only, but we stop that way of update because the pull became too long when the image was updated ( when it was developped, maybe now it can be a good solution )

**Comment by acherm** [comment]
Based on our discussions, here is the idea: 
 * not decompressing the Linux kernel archive (do it at runtime, it should save ~600Mb)
 * not installing upfront all Debian packages (saving some spaces, we need to quantify it), but rather install deb at runtime 

Overall, we will save some spaces and the Docker image will be much lighter. We will have a "small" overhead since we need to decompress and install deb packages 

As a concrete task:
 * we need to rewrite TPDIM.py as well as Docker files to make it more understandable, usable, avoid some strange steps, and take our improvements into account (note: would be nice to have an option to pull or just changing the local image) 
 * we need to adapt the Python scripts (eg for decompressing the archive) side note: the time needed to decompress/install should not count as part of compilation time
 * we need to test test test for ensuring that (1) we have the same environment (gcc version, libc version, etc.) (2) it does compile and send all information to the database (3) quantify a bit the "overhead"
