### ISSUE TITLE
Compilations pre-set options

### ISSUE THREAD

**Issue by alemasle** [TuxML/ProjetIrma#98]
Make the propositions for pre-set options here.

**Comment by alemasle** [comment]
the ones we have are:
CONFIG_64BIT=y
CONFIG_DEBUG_INFO=n
CONFIG_GCOV_PROFILE_ALL=n
CONFIG_KASAN=n
CONFIG_UBSAN_SANITIZE_ALL=n
CONFIG_RELOCATABLE=n
CONFIG_XFS_DEBUG=n
CONFIG_AIC7XXX_BUILD_FIRMWARE=n
CONFIG_AIC79XX_BUILD_FIRMWARE=n
CONFIG_WANXL_BUILD_FIRMWARE=n

**Comment by FAMILIAR-project** [comment]
New list: 
CONFIG_64BIT=y
CONFIG_DEBUG_INFO=n
CONFIG_DEBUG_INFO_SPLIT=n
CONFIG_UBSAN_SANITIZE_ALL=n
CONFIG_GCOV_PROFILE_ALL=n
CONFIG_DEBUG_INFO_REDUCED=n
CONFIG_RANDOMIZE_BASE=n
CONFIG_X86_NEED_RELOCS=n
CONFIG_KASAN_OUTLINE=n
CONFIG_UBSAN_ALIGNMENT=n
CONFIG_USB_SERIAL_OPTICON=n
CONFIG_KASAN=n
CONFIG_KCOV_INSTRUMENT_ALL=n
CONFIG_XFS_DEBUG=n
CONFIG_MAXSMP=n
CONFIG_FW_LOADER_USER_HELPER=n
CONFIG_STRICT_MODULE_RWX=n  
CONFIG_DEBUG_INFO_DWARF4=n
CONFIG_AIC7XXX_BUILD_FIRMWARE=n
CONFIG_AIC79XX_BUILD_FIRMWARE=n
CONFIG_WANXL_BUILD_FIRMWARE=n

notes:
 * based on machine learning results (top 15) 
 * I've reviewed all documentation about options, all make absolutely sense since they all have an influence on sizes (more to come) 
 * there are more but it's already interesting to see the effect

**Comment by alemasle** [comment]
Do i update the docker image and the IGRIDA image right now ?

**Comment by FAMILIAR-project** [comment]
Yes, please

**Comment by alemasle** [comment]
Done!

**Comment by FAMILIAR-project** [comment]
Two new options to preset: 
CONFIG_LOCK_STAT=n 
CONFIG_X86_VSMP=n

**Comment by alemasle** [comment]
I am on it

**Comment by alemasle** [comment]
added

**Comment by FAMILIAR-project** [comment]
The story continues -- I've tried to include: 
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
CONFIG_OPTIMIZE_INLINING=y
CONFIG_SLOB=y

these options are from tinyconfig but are not identified by the learning (for some reasons that are out of the scope of this issue).
